//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.05 at 05:16:00 PM GMT 
//


package ie.cit.cloud.promotion;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ie.cit.cloud.promotion package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PromotionRequestProductDiscount_QNAME = new QName("http://cloud.cit.ie/promotion", "productDiscount");
    private final static QName _PromotionRequestProductQuantity_QNAME = new QName("http://cloud.cit.ie/promotion", "productQuantity");
    private final static QName _PromotionRequestProductCode_QNAME = new QName("http://cloud.cit.ie/promotion", "productCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ie.cit.cloud.promotion
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PromotionResponse }
     * 
     */
    public PromotionResponse createPromotionResponse() {
        return new PromotionResponse();
    }

    /**
     * Create an instance of {@link PromotionRequest }
     * 
     */
    public PromotionRequest createPromotionRequest() {
        return new PromotionRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cloud.cit.ie/promotion", name = "productDiscount", scope = PromotionRequest.class)
    public JAXBElement<BigDecimal> createPromotionRequestProductDiscount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PromotionRequestProductDiscount_QNAME, BigDecimal.class, PromotionRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cloud.cit.ie/promotion", name = "productQuantity", scope = PromotionRequest.class)
    public JAXBElement<BigInteger> createPromotionRequestProductQuantity(BigInteger value) {
        return new JAXBElement<BigInteger>(_PromotionRequestProductQuantity_QNAME, BigInteger.class, PromotionRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cloud.cit.ie/promotion", name = "productCode", scope = PromotionRequest.class)
    public JAXBElement<BigInteger> createPromotionRequestProductCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_PromotionRequestProductCode_QNAME, BigInteger.class, PromotionRequest.class, value);
    }

}
