//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.05 at 04:36:34 PM GMT 
//


package ie.cit.cloud.voucher;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ie.cit.cloud.voucher package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VoucherRequestProductQuantity_QNAME = new QName("http://cloud.cit.ie/voucher", "productQuantity");
    private final static QName _VoucherRequestProductDiscount_QNAME = new QName("http://cloud.cit.ie/voucher", "productDiscount");
    private final static QName _VoucherRequestProductCode_QNAME = new QName("http://cloud.cit.ie/voucher", "productCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ie.cit.cloud.voucher
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VoucherRequest }
     * 
     */
    public VoucherRequest createVoucherRequest() {
        return new VoucherRequest();
    }

    /**
     * Create an instance of {@link VoucherResponse }
     * 
     */
    public VoucherResponse createVoucherResponse() {
        return new VoucherResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cloud.cit.ie/voucher", name = "productQuantity", scope = VoucherRequest.class)
    public JAXBElement<BigInteger> createVoucherRequestProductQuantity(BigInteger value) {
        return new JAXBElement<BigInteger>(_VoucherRequestProductQuantity_QNAME, BigInteger.class, VoucherRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cloud.cit.ie/voucher", name = "productDiscount", scope = VoucherRequest.class)
    public JAXBElement<BigDecimal> createVoucherRequestProductDiscount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_VoucherRequestProductDiscount_QNAME, BigDecimal.class, VoucherRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cloud.cit.ie/voucher", name = "productCode", scope = VoucherRequest.class)
    public JAXBElement<BigInteger> createVoucherRequestProductCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_VoucherRequestProductCode_QNAME, BigInteger.class, VoucherRequest.class, value);
    }

}
