//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.28 at 03:57:28 PM GMT 
//


package ie.cit.cloud.pointofsale;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ie.cit.cloud.pointofsale package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ie.cit.cloud.pointofsale
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SalesTransactionRequest }
     * 
     */
    public SalesTransactionRequest createSalesTransactionRequest() {
        return new SalesTransactionRequest();
    }

    /**
     * Create an instance of {@link SalesTransactionRequest.Item }
     * 
     */
    public SalesTransactionRequest.Item createSalesTransactionRequestItem() {
        return new SalesTransactionRequest.Item();
    }

    /**
     * Create an instance of {@link PromotionResponse }
     * 
     */
    public PromotionResponse createPromotionResponse() {
        return new PromotionResponse();
    }

    /**
     * Create an instance of {@link VoucherResponse }
     * 
     */
    public VoucherResponse createVoucherResponse() {
        return new VoucherResponse();
    }

    /**
     * Create an instance of {@link CreditcardResponse }
     * 
     */
    public CreditcardResponse createCreditcardResponse() {
        return new CreditcardResponse();
    }

    /**
     * Create an instance of {@link LoyaltyResponse }
     * 
     */
    public LoyaltyResponse createLoyaltyResponse() {
        return new LoyaltyResponse();
    }

}
