//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.28 at 03:57:28 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cloud.cit.ie/pointofsale")
package ie.cit.cloud.pointofsale;

